FROM almalinux:9.0
LABEL os="almalinux"
LABEL author="tinu"
LABEL content="almalinux with PowerShell 7"
LABEL release-date="2024-04-10 14:16:31"
LABEL version="0.0.1-beta"
ENV container docker
RUN echo "*** Build Image ***"
RUN dnf clean all -y
RUN dnf update -y
RUN echo "> Install PowerShell 7"
RUN curl https://packages.microsoft.com/config/rhel/9.0/prod.repo | tee /etc/yum.repos.d/microsoft.repo
RUN dnf install --assumeyes powershell
RUN pwsh -Command "& {Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -SourceLocation https://www.powershellgallery.com/api/v2}"
RUN pwsh -Command "& {Install-Module -Name PSNetTools, linuxinfo}"
COPY profile.ps1 /opt/microsoft/powershell/7
RUN echo "*** Build finished ***"
