FROM ubuntu:latest
LABEL os="ubuntu"
LABEL author="tinu"
LABEL content="ubuntu with PowerShell 7"
LABEL release-date="2024-04-10 14:32:53"
LABEL version="0.0.1-beta"
ENV container docker
RUN echo "*** Build Image ***"
RUN apt-get clean all
RUN apt-get update
RUN echo "> Install PowerShell 7"
RUN apt-get install -y wget apt-transport-https software-properties-common
RUN wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y powershell
COPY profile.ps1 /opt/microsoft/powershell/7
RUN pwsh -Command "& {Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -SourceLocation https://www.powershellgallery.com/api/v2}"
RUN pwsh -Command "& {Install-Module -Name PSNetTools, linuxinfo}"
RUN echo "*** Build finished ***"
